addons:
  sonarcloud:
    organization: "theghostshell"
    token: $SONAR_TOKEN

dist: trusty
language: java
jdk:
- openjdk8
script:
- "./gradlew assemble"
- "./gradlew check"
- "./gradlew codeCoverageReport"
- "./gradlew jacocoTestReport"
- "sonar-scanner -X"
after_success:
- bash <(curl -s https://codecov.io/bash)
#env:
#  matrix:
#    secure: TFMwRPttu1rkKL2ie7rZvrFWCXK/F2noodtfSz8Jq4KtnJ5vttRtk9wCQKJDob6hVlhzL9JTeSX4ZV2fhFKEJsAo5gHLUJ+/FeQM1a6x5YP86wO1cqJy9tty2qGbQ5gb8rSxyrIiAcOJxW2viVye3irbvBnqir4LhwJkTyQs13yN18vo6Ga7XBoHgq+NDmtsRbwVQbkg2nnJe+GQR0/5bd8KwJOqJvtD145KhFYlV4kxRKomJRGyP/HmzAqVc2TIZtyH3X7YgeWqJsBgGYiqeyZYxM1CZo4rTUgT+m36kkGczoUGeeeua0LHfvKtUOQXnAtc8m5OiNoQyOABfsQKUSBuVoawgLDm81SqmCcErJhGTuBtW16vVPPnqV7kn/7LIuY+3CPn0ZhOCuLR6NY2D4stVjbIE71TxdKEiuomTO+ZDh/imfjzj5jfUn4N5iEjPjXXAaNuWEtd0M51QIEBZkPv0AVqU4P0vFhxcJCApI8DE4dK2z6/xRcmQRsFEO9ved31oMRLOPiYIefk4xS9LastKi+o800m9eUXjMqp8hrS3iJIcV6VWE500bdXA1Pc9MsMdV0F+mC0XuyOhKLijqQOVSrhzzgd7F2w/xDzyjg1aAqcXDY4xpHNp9/O1513a+M0vvLJYsDmmUA6gilIL1BdiWx9ivY5A19/l+WCyyA=
