language: java
jdk:
  - openjdk8
script:
  - ./gradlew assemble
  - ./gradlew check
  - ./gradlew codeCoverageReport
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)