addons:
  sonarcloud:
    organization: "theghostshell"
    token: $SONAR_TOKEN

dist: trusty
language: java
jdk:
- openjdk8
script:
- "./gradlew assemble"
- "./gradlew check"
- "sonar-scanner -X"
- "./gradlew codeCoverageReport"
- "./gradlew jacocoTestReport"
- "./gradlew jacocoIntegrationTestReport"
- "./gradlew jacocoTestCoverageVerification"
after_success:
- bash <(curl -s https://codecov.io/bash) -f "*.html" -s "./build/reports"